package mainstreet.deployment;

public enum ServingGenerationPromotionFailureCategory {
    SNAPSHOT_NOT_FOUND,
    CONTROL_NOT_INITIALIZED,
    CONTROL_NOT_STABLE,
    CURRENT_GENERATION_MISMATCH,
    ACTIVE_REQUIREMENT_EVIDENCE_MISSING,
    ACTIVE_REQUIREMENT_EVIDENCE_AMBIGUOUS,
    SEMANTIC_MATERIALISATION_INCOMPLETE,
    EXECUTABLE_SUPPORT_INCOMPLETE,
    REQUEST_IDENTITY_CONFLICT,
    TRANSITION_NOT_FOUND,
    RECONCILIATION_REQUIRED,
    PERSISTENCE_FAILURE
}
