package mainstreet.surface;

/** Exact fail-closed current audience-admission failure. */
public enum AudienceObservationAdmissionFailure {
    AUTHENTICATION_NOT_CURRENT,
    AUTHENTICATION_CURRENTNESS_UNRESOLVED,
    MERCHANT_ASSOCIATION_UNSATISFIED,
    MERCHANT_ASSOCIATION_UNRESOLVED,
    CONTEXTUAL_AUTHORITY_UNAVAILABLE_OR_UNRESOLVED,
    PLATFORM_PROTECTION_UNSATISFIED,
    PLATFORM_PROTECTION_UNRESOLVED,
    UNSUPPORTED_AUDIENCE_MODE
}
