package mainstreet.surface;

/** Exact fail-closed causes for closed observation-subject establishment. */
public enum AudienceObservationContextEstablishmentFailure {
    SUBJECT_SCOPE_MISMATCH,
    AUTHENTICATION_REQUIRED,
    AUTHENTICATION_PRINCIPAL_MISMATCH,
    AUTHENTICATION_SESSION_UNRESOLVED,
    AUTHENTICATION_SESSION_IDENTITY_MISMATCH,
    AUTHENTICATION_SESSION_ESTABLISHMENT_MISMATCH,
    CONTEXTUAL_PROOF_OWNER_OR_KIND_MISMATCH,
    CONTEXTUAL_PROOF_CLASS_MISMATCH,
    CONTEXTUAL_PROOF_REQUEST_MISMATCH,
    CONTEXTUAL_PROOF_SCOPE_MISMATCH,
    CONTEXTUAL_PROOF_PRINCIPAL_MISMATCH,
    CONTEXTUAL_PROOF_ACCESS_BINDING_INVALID,
    CONTRIBUTION_DEFINITION_MISMATCH,
    CONTRIBUTION_RUNTIME_BINDING_MISMATCH,
    CONTRIBUTION_AUDIENCE_MISMATCH,
    CONTRIBUTION_REQUEST_MISMATCH,
    CONTRIBUTION_SCOPE_MISMATCH,
    CONTRIBUTION_DUPLICATE
}
