package mainstreet.surface;

/** Exact fail-closed causes for trusted observation request establishment. */
public enum ObservationRequestEstablishmentFailure {
    API_CONTRACT_UNREGISTERED,
    API_CONTRACT_NOT_QUERY,
    API_SCOPE_ESTABLISHMENT_FAILED,
    API_SCOPE_NOT_MERCHANT,
    ACTIVE_CONFIGURATION_UNRESOLVED,
    ACTIVE_CONFIGURATION_SCOPE_MISMATCH,
    SEMANTIC_RELEASE_NOT_MATERIALISED,
    PROJECTION_REGISTRY_RELEASE_MISMATCH,
    EXPOSURE_REGISTRY_RELEASE_MISMATCH
}
