package mainstreet.surface;

/** Stable internal reason classification for serviceability decisions. */
public enum ProjectionServiceabilityReasonCode {
    EXACT_CONTRACT_UNRESOLVED,
    EXACT_READ_USE_UNRESOLVED,
    POLICY_EVALUATOR_UNRESOLVED,
    EVIDENCE_SET_MISMATCH,
    SOURCE_UNAVAILABLE,
    SOURCE_EVIDENCE_MISSING,
    SOURCE_EVIDENCE_PARTIAL,
    SOURCE_EVIDENCE_CORRUPT,
    SOURCE_EVIDENCE_UNVERIFIABLE,
    SOURCE_KNOWN_STALE,
    SOURCE_REVOKED,
    REQUIRED_SOURCE_NOT_CURRENT,
    REDUCED_TRUTHFUL_REPRESENTATION,
    POLICY_EVALUATION_FAILED
}
