package mainstreet.semantic.configuration;

/** Distinct recoverable/fail-closed Configuration Revision persistence outcomes. */
public enum ConfigurationRevisionFailureCategory {
    INITIAL_CONFIGURATION_INTENT_NOT_FOUND,
    INITIAL_INTENT_IDENTITY_CONFLICT,
    CONFIGURATION_REVISION_IDENTITY_CONFLICT,
    CONFIGURATION_VERSION_CONFLICT,
    UNSUPPORTED_INITIAL_INTENT,
    ORDINARY_SEMANTIC_RELEASE_UNAVAILABLE,
    BASE_CONFIGURATION_REVISION_NOT_FOUND,
    CHANGE_SET_IDENTITY_CONFLICT,
    CHANGE_AUTHORIZATION_REJECTED,
    PERSISTENCE_FAILURE
}
