package mainstreet.semantic.configuration;

/**
 * Stable activation outcome classifications required by the configuration
 * lifecycle contract.
 */
public enum ConfigurationActivationStatus {
    VALIDATION_REJECTION,
    APPROVAL_REQUIRED,
    AUTHORISATION_REJECTION,
    ACTIVATION_CONFLICT,
    PACKAGE_MISMATCH,
    SEMANTIC_RELEASE_NOT_ADMITTED_FOR_NEW_CONFIGURATION,
    SEMANTIC_RELEASE_NOT_ADMITTED_FOR_NEW_BUSINESS_ACTIVITY,
    SEMANTIC_RELEASE_NOT_MATERIALISED_BY_SERVING_DEPLOYMENT,
    EXECUTABLE_SUPPORT_INCOMPLETE,
    DEPLOYMENT_ADMISSION_CONFLICT,
    TECHNICAL_FAILURE_BEFORE_ACTIVATION_COMMIT,
    EXECUTION_UNCERTAIN,
    SUCCESS
}
