package mainstreet.onboarding;

/**
 * Distinct reasons an exact final review cannot proceed to atomic submission.
 */
public enum OnboardingSubmissionBlocker {
    CASE_NOT_FOUND,
    STALE_REVIEW,
    REVIEW_CONTENT_MISMATCH,
    CASE_NOT_IN_PROGRESS,
    COMPLETION_POLICY_MISSING,
    INCOMPLETE_SUPPORTED_INTENT,
    DEFINITION_REVIEW_REQUIRED,
    ANSWER_INVALID_FOR_QUESTION_DEFINITION,
    UNRESOLVED_NOT_SURE,
    UNRESOLVED_VARIES,
    UNSUPPORTED_INTENT,
    AUTHENTICATION_REQUIRED,
    AUTHORISATION_REJECTION,
    ACCOUNT_OPERATION_RESTRICTED,
    INITIAL_ONBOARDING_NOT_APPLICABLE
}
