package grandrue.semantic.configuration;

/**
 * Stable rejection categories for Configuration Revision approval.
 */
public enum ConfigurationRevisionApprovalFailureCategory {
    AUTHENTICATED_PRINCIPAL_REQUIRED,
    REVISION_NOT_FOUND_OR_WRONG_MERCHANT,
    REVISION_NOT_APPLICABLE_NON_INITIAL,
    VALIDATION_EVIDENCE_NOT_FOUND_OR_AFFINITY_MISMATCH,
    PACKAGE_EVIDENCE_NOT_FOUND_OR_AFFINITY_MISMATCH,
    IMPACT_REVIEW_EVIDENCE_NOT_FOUND_OR_AFFINITY_MISMATCH,
    BLOCKING_IMPACT_REMAINS,
    CURRENT_CONTROLLER_NOT_FOUND,
    APPROVING_PRINCIPAL_NOT_CURRENT_CONTROLLER,
    APPROVAL_REQUEST_IDENTITY_CONFLICT,
    APPROVAL_CONCURRENCY_CONFLICT,
    PERSISTENCE_FAILURE
}